# 配置tomcat请求最大头
server:
  max-http-header-size: 1048576
  port: 9999

#关闭thymeleaf缓存
spring:
  profiles:
    active: dev
  redis:
    password:
    host: localhost
    port: 6379
  cache: redis


# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true
  typeEnumsPackage: com.baseframework.pojo.**.*
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#Spring Boot 默认是不注入这些属性值的，需要自己绑定
druid:
  #druid 数据源专有配置
  initialSize: 5
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache
  poolPreparedStatements: true
  #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
  #如果运行时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
  #则导入 log4j 依赖即可，Maven 地址： https://mvnrepository.com/artifact/log4j/log4j
  filters: stat,wall,config
  #指定每个连接上PSCache的大小
  maxPoolPreparedStatementPerConnectionSize: 20
  #合并多个DruidDataSource的监控数据
  useGlobalDataSourceStat: true
  #通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000